### ISSUE TITLE
Segfault on creating Zookeeper Client

### ISSUE THREAD

**Issue by gregbuehler** [newrelic/nri-kafka#62]
##### Description of the problem

nri-kafka produces a segfault.

```
$ sudo /var/db/newrelic-infra/newrelic-integrations/bin/nr-kafka -consumer_offset
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x73a092]

goroutine 1 [running]:
github.com/newrelic/nri-kafka/src/conoffsetcollect.Collect(0x0, 0x0, 0xc42009c370, 0x0, 0x0)
    /data/jenkins/infra-integrations-nri-kafka-release-linux-package-36/go/src/github.com/newrelic/nri-kafka/src/conoffsetcollect/collect.go:25 +0x52
main.main()
    /data/jenkins/infra-integrations-nri-kafka-release-linux-package-36/go/src/github.com/newrelic/nri-kafka/src/kafka.go:43 +0x27f
```

##### OS

- [x ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)

**Comment by camdencheek** [comment]
Should be fixed in the latest version
